projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - ./**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: eu-west-1
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
